const TWENTY_FOUR_HOURS = 24 * 60 * 60 * 1000;
const MINIMUM_APPROVAL_PERCENTAGE = 0.75;
const MINIMUM_REQUIRED_VOTES = 30;

module.exports = {
  TWENTY_FOUR_HOURS,
  MINIMUM_APPROVAL_PERCENTAGE,
  MINIMUM_REQUIRED_VOTES,
};
