// time constants
const TWENTY_FOUR_HOURS = 24 * 60 * 60 * 1000;
const ONE_MINUTE = 60 * 1000

const MINIMUM_APPROVAL_PERCENTAGE = 0.70;
const MINIMUM_REQUIRED_VOTES = 30;
const DAO_VOTE_POLL_DURATION = TWENTY_FOUR_HOURS;

// debug
// const MINIMUM_APPROVAL_PERCENTAGE = 0.5;
// const MINIMUM_REQUIRED_VOTES = 0;
// const DAO_VOTE_POLL_DURATION = ONE_MINUTE;

module.exports = {
  TWENTY_FOUR_HOURS,
  MINIMUM_APPROVAL_PERCENTAGE,
  MINIMUM_REQUIRED_VOTES,
  DAO_VOTE_POLL_DURATION,
};
